version: '3.7'
services:
    portainer:
     image: portainer/portainer
     restart: always
     ports:
      - 80:9000
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainerdata:/data
